# Generated by Django 3.2.13 on 2022-04-29 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_dailyroutine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routine',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='dailyroutine',
            name='date',
            field=models.DateField(default=datetime.datetime.now, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyroutine',
            unique_together={('date', 'routine')},
        ),
        migrations.RemoveField(
            model_name='dailyroutine',
            name='day',
        ),
    ]
