# Generated by Django 3.2.13 on 2022-04-29 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_auto_20220429_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyroutine',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='dailyroutine',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
